
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: arg-gitops
  description: Contains the ArgoCD manifests for arg
  annotations:
    argocd/app-name: arg-gitops
    backstage.io/kubernetes-id: arg-gitops
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: BlackMamba97s/arg-gitops
spec:
  type: gitops
  system: argocd
  lifecycle: production
  owner: BlackMamba97
  dependsOn:
    - component:default/backstagedocs
