apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "arg"
spec:
  destination:
    namespace: system:janus-idp
    server: https://rhsummitdemos-dns-ylk490nk.hcp.germanywestcentral.azmk8s.io:443
  project: default
  source:
    path: manifests/base
    repoURL: https://github.com/BlackMamba97s/arg
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
